### ISSUE TITLE
English 

### ISSUE THREAD

**Issue by Justdigit** [tianma8023/XMiuiClock#1]
Maybe you can make it in English?

**Comment by Coreyrufus** [comment]
https://github.com/tianma8023/XMiuiClock/blob/master/README.md#screenshots

**Comment by Justdigit** [comment]
Looking great.... Thanks!

Op 28 april 2019 04:29:28 schreef Coreyrufus <notifications@github.com>:

**Comment by tianma8023** [comment]
@justintime1976 English translation will be added in the next version. :)

**Comment by tianma8023** [comment]
@justintime1976 hi, the current latest version [1.3.0](https://github.com/tianma8023/XMiuiClock/releases/tag/1.0.3) has solved this issue.
