### ISSUE TITLE
How you deal with Xsharepreference??

### ISSUE THREAD

**Issue by Android1500** [tianma8023/XMiuiClock#12]
Actually i am developing a module but Xsharedpreference can't take data from sharepreferences "/data/user/0/packageName/shared_prefs/user_prefs.xml" coz as we knw its coz protection of SDK 24 or Higer i tried this way too...

if (Build.VERSION.SDK_INT > 23) {
File Prefile1;
File Prefile2;
Prefile1 = new File("/data/user/0/packageName/shared_prefs/user_prefs.xml");
Prefile2 = new File("/data/user_de/0/packageName/shared_prefs/user_prefs.xml");
if (Prefile1.exists() && Prefile1.canRead()) {

                pref = new XSharedPreferences(Prefile1); // For Android 7.0 or Higer

            } else if (!Prefile2.exists() || !Prefile2.canRead()){

                pref = new XSharedPreferences("packageName", "user_prefs");
                pref.makeWorldReadable();
                pref.reload();

            }else {
                pref = new XSharedPreferences(Prefile2);
                pref.makeWorldReadable();
                pref.reload();
                
                 }

        }else {
            pref = new XSharedPreferences("com.yuvi.mask", "user_prefs");
            pref.makeWorldReadable();
            pref.reload();
        }

        return pref;
    }
    return pref; }
                
                
                but still can't read user_prefs.xml by Xsharedpreference
                please help bro

**Comment by tianma8023** [comment]
@Android1500 
This caused because of the ["Direct Boot mode"](https://developer.android.com/training/articles/direct-boot#java) since Android N (api >= 24).

And Google give us the [solution](https://developer.android.com/training/articles/direct-boot#access) offically:
```java
Context directBootContext = appContext.createDeviceProtectedStorageContext();
// Access appDataFilename that lives in device encrypted storage
FileInputStream inStream = directBootContext.openFileInput(appDataFilename);
// Use inStream to read content...
```

But it not completed, here is my solution in this module(XMiTools):
1. [Create device protected storage context in BaseActivity](https://github.com/tianma8023/XMiTools/blob/374b5f3bae9292714b3917a6bcf4dadf1c5937f2/app/src/main/java/com/tianma/tweaks/miui/app/base/BaseActivity.java#L14)

**Comment by tianma8023** [comment]
@Android1500
This caused because of the ["Direct Boot mode"](https://developer.android.com/training/articles/direct-boot#java) since Android N (api >= 24).

And Google give us the [solution](https://developer.android.com/training/articles/direct-boot#access) offically:
```java
Context directBootContext = appContext.createDeviceProtectedStorageContext();
// Access appDataFilename that lives in device encrypted storage
FileInputStream inStream = directBootContext.openFileInput(appDataFilename);
// Use inStream to read content...
```

But it isn't completed in my opinion, here is my solution in this module(XMiTools):
1. [Create device protected storage context in BaseActivity](https://github.com/tianma8023/XMiTools/blob/374b5f3bae9292714b3917a6bcf4dadf1c5937f2/app/src/main/java/com/tianma/tweaks/miui/app/base/BaseActivity.java#L14)
    ```java
    protected void attachBaseContext(Context newBase) {
        Context context = newBase;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            context = ContextUtils.getProtectedContext(newBase);
        }
        super.attachBaseContext(context);
    }
    ```
2. [Set specific SharedPreferences profile name in BasePreferenceFragment](https://github.com/tianma8023/XMiTools/blob/374b5f3bae9292714b3917a6bcf4dadf1c5937f2/app/src/main/java/com/tianma/tweaks/miui/app/base/BasePreferenceFragment.java#L25):
   ```java
   public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
        PreferenceManager pm = getPreferenceManager();
        pm.setSharedPreferencesName(AppConst.X_MIUI_CLOCK_PREFS_NAME);
    }
   ```
3. [Set preference file world writable](https://github.com/tianma8023/XMiTools/blob/374b5f3bae9292714b3917a6bcf4dadf1c5937f2/app/src/main/java/com/tianma/tweaks/miui/app/fragment/GeneralSettingsFragment.kt#L90)
    ```kotlin
    val context: Context = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
        // API >= 24 (Android 7.0+)
        // dataDir: /data/user_de/0/<package_name>/
        // spDir: /data/user_de/0/<package_name>/shared_prefs/
        // spFile: /data/user_de/0/<package_name>/shared_prefs/<preferences_name>.xml
        ContextUtils.getProtectedContext(mActivity.applicationContext)
    } else {
        // API < 24, there is no data encrypt.
        // dataDir: /data/data/<package_name>/
        mActivity.applicationContext
    }
    val prefsFile = StorageUtils.getSharedPreferencesFile(context, AppConst.X_MIUI_CLOCK_PREFS_NAME)
    StorageUtils.setFileWorldWritable(prefsFile, 2)
    ```
4. [Get XSharedPreference by profiel name](https://github.com/tianma8023/XMiTools/blob/374b5f3bae9292714b3917a6bcf4dadf1c5937f2/app/src/main/java/com/tianma/tweaks/miui/utils/XSPUtils.java#L53)
    ```java
    public static XSharedPreferences getXSharedPreferences() {
        File prefsFile = new File("/data/user_de/0/" + BuildConfig.APPLICATION_ID + "/shared_prefs/" + AppConst.X_MIUI_CLOCK_PREFS_NAME + ".xml");
        XSharedPreferences xsp;
        if (prefsFile.exists()) { // Android 7.0+
            xsp = new XSharedPreferences(prefsFile);
        } else { // below Android 7.0
            xsp = new XSharedPreferences(BuildConfig.APPLICATION_ID);
        }
        try {
            xsp.makeWorldReadable();
        } catch (Throwable t) {
            XLog.e("", t);
        }
        return xsp;
    }
    ```

For more detailed information, you can view this commit: [8e9142a](https://github.com/tianma8023/XMiTools/commit/8e9142a73f225d69da0f63d8553f122e282a8fce)

**Comment by Android1500** [comment]
> @Android1500
> This caused because of the ["Direct Boot mode"](https://developer.android.com/training/articles/direct-boot#java) since Android N (api >= 24).
> 
> And Google give us the [solution](https://developer.android.com/training/articles/direct-boot#access) offically:
> 
> ```java
> Context directBootContext = appContext.createDeviceProtectedStorageContext();
> // Access appDataFilename that lives in device encrypted storage
> FileInputStream inStream = directBootContext.openFileInput(appDataFilename);
> // Use inStream to read content...
> ```
> 
> But it isn't completed in my opinion, here is my solution in this module(XMiTools):
> 
> 1. [Create device protected storage context in BaseActivity](https://github.com/tianma8023/XMiTools/blob/374b5f3bae9292714b3917a6bcf4dadf1c5937f2/app/src/main/java/com/tianma/tweaks/miui/app/base/BaseActivity.java#L14)
>    ```java
>    protected void attachBaseContext(Context newBase) {
>        Context context = newBase;
>        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
>            context = ContextUtils.getProtectedContext(newBase);
>        }
>        super.attachBaseContext(context);
>    }
>    ```
> 2. [Set specific SharedPreferences profile name in BasePreferenceFragment](https://github.com/tianma8023/XMiTools/blob/374b5f3bae9292714b3917a6bcf4dadf1c5937f2/app/src/main/java/com/tianma/tweaks/miui/app/base/BasePreferenceFragment.java#L25):
>    ```java
>    public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
>         PreferenceManager pm = getPreferenceManager();
>         pm.setSharedPreferencesName(AppConst.X_MIUI_CLOCK_PREFS_NAME);
>     }
>    ```
> 3. [Set preference file world writable](https://github.com/tianma8023/XMiTools/blob/374b5f3bae9292714b3917a6bcf4dadf1c5937f2/app/src/main/java/com/tianma/tweaks/miui/app/fragment/GeneralSettingsFragment.kt#L90)
>    ```kotlin
>    val context: Context = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
>        // API >= 24 (Android 7.0+)
>        // dataDir: /data/user_de/0/<package_name>/
>        // spDir: /data/user_de/0/<package_name>/shared_prefs/
>        // spFile: /data/user_de/0/<package_name>/shared_prefs/<preferences_name>.xml
>        ContextUtils.getProtectedContext(mActivity.applicationContext)
>    } else {
>        // API < 24, there is no data encrypt.
>        // dataDir: /data/data/<package_name>/
>        mActivity.applicationContext
>    }
>    val prefsFile = StorageUtils.getSharedPreferencesFile(context, AppConst.X_MIUI_CLOCK_PREFS_NAME)
>    StorageUtils.setFileWorldWritable(prefsFile, 2)
>    ```
> 4. [Get XSharedPreference by profiel name](https://github.com/tianma8023/XMiTools/blob/374b5f3bae9292714b3917a6bcf4dadf1c5937f2/app/src/main/java/com/tianma/tweaks/miui/utils/XSPUtils.java#L53)
>    ```java
>    public static XSharedPreferences getXSharedPreferences() {
>        File prefsFile = new File("/data/user_de/0/" + BuildConfig.APPLICATION_ID + "/shared_prefs/" + AppConst.X_MIUI_CLOCK_PREFS_NAME + ".xml");
>        XSharedPreferences xsp;
>        if (prefsFile.exists()) { // Android 7.0+
>            xsp = new XSharedPreferences(prefsFile);
>        } else { // below Android 7.0
>            xsp = new XSharedPreferences(BuildConfig.APPLICATION_ID);
>        }
>        try {
>            xsp.makeWorldReadable();
>        } catch (Throwable t) {
>            XLog.e("", t);
>        }
>        return xsp;
>    }
>    
> 
> For more detailed information, you can view this commit: [8e9142a](https://github.com/tianma8023/XMiTools/commit/8e9142a73f225d69da0f63d8553f122e282a8fce)

Thanks I Appericate but I am little bit Confuse why we need to ""add Set preference file world writable"" or ""readable""?? As I knw this method use for SDK > 24  coz read or write user_prefs.xml  I am making a module which hook parm in Telephony Classes But i face issue if i install my module in sdk less than 24 than it changing parm which i give through My app like i put random device id then its changed but when i installed same module greater than 24 SDK its not change coz of Context.MODE_WORLD_READABLE not support on SDK which greater than 24 so I use Context.MODE_PIRVATE and coz private XsharePreference can't read "user_prefs.xml" Any Suggestion!!



`    if (Build.VERSION.SDK_INT > 24){
            
            pref = getSharedPreferences(USER_PREFS, Context.MODE_PRIVATE);
        }
        else {

            pref = getSharedPreferences(USER_PREFS, Context.MODE_WORLD_READABLE);
            
            
        }

        
            btn_imei.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                edt = pref.edit();
                String imei = edt_imei.getText().toString().trim();
                edt.putString("imei_val", imei);
                edt.commit();
                tx_imei1.setText("IMEI: " + imei);
                edt.commit();

            }
        });

    }`

**Comment by tianma8023** [comment]
@Android1500 Sorry for the soooo late reply. 

Recently, i found out the solution above is not exactly correct.

Here are the all cases:
1. If host app (the app you hooked) is the system app, XSharedPreferences in host app can read sp file if it's world-readable. Just like I mentioned before.
2. If host app is user app (isn't system app). You can try [RemotePreferences](https://github.com/apsun/RemotePreferences) or [spx](https://github.com/zpp0196/spx) for accessing inter-app sharedpreferences.

**Comment by Android1500** [comment]
> @Android1500 Sorry for the soooo late reply. 
> 
> 
> 
> Recently, i found out the solution above is not exactly correct.
> 
> 
> 
> Here are the all cases:
> 
> 1. If host app (the app you hooked) is the system app, XSharedPreferences in host app can read sp file if it's world-readable. Just like I mentioned before.
> 
> 2. If host app is user app (isn't system app). You can try [RemotePreferences](https://github.com/apsun/RemotePreferences) or [spx](https://github.com/zpp0196/spx) for accessing inter-app sharedpreferences.
> 
> 

Thanks for your response i see it late but i already impeliment new Xshared and recently i removed new Xshared and using RemotePreference which work great.

**Comment by tianma8023** [comment]
@Android1500 My pleasure. ^_^
