### ISSUE TITLE
LSPosed and font

### ISSUE THREAD

**Issue by yzctzl** [tianma8023/XMiuiClock#14]
大佬你好，这个模块可以使用 LSPosed 安装吗？
截图中的字体太漂亮了，请问叫啥名字呀，感谢！

**Comment by tianma8023** [comment]
@yzctzl 字体名：筑紫A丸 ，可以在网上(比如酷安)找找资源，或者是去 “宁静之雨” 微信公众号里面看看有没有字体资源
