### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by No-ideaaa** [tianma8023/XMiuiClock#3]
锁屏显秒更新系统后无效，MIUI10 9.5.9，红米5plus，状态栏时间格式一直无效，只能显秒

**Comment by No-ideaaa** [comment]
Edxposed sandhook4.12，riru18

**Comment by tianma8023** [comment]
@xiaomengxinyo 已知Bug，下个版本修复。

**Comment by No-ideaaa** [comment]
@tianma8023 大佬辛苦了

**Comment by tianma8023** [comment]
@xiaomengxinyo 目前最新版 [1.0.4](https://github.com/tianma8023/XMiuiClock/releases/tag/1.0.4) 已经修复了没能适配的问题。

**Comment by No-ideaaa** [comment]
@tianma8023 好嘞，辛苦了

**Comment by No-ideaaa** [comment]
@tianma8023 现在只有时间格式无法使用，不知道是什么原因，一开始是可以用的，后来重启了一下，就用不了了，其他功能都可以用

**Comment by tianma8023** [comment]
@xiaomengxinyo 截图看一下你的模块设置。

**Comment by No-ideaaa** [comment]
@tianma8023 大哥留下你的邮箱或者QQ，Github我不会发图片😂

**Comment by tianma8023** [comment]
@xiaomengxinyo 
- 电脑端的话，直接把图片拖拽进输入区域就行。
- 手机端的话，手机浏览器（推荐Chrome）切换到桌面版，然后点一下下面的 `Attach files by dragging & dropping, selecting or pasting them.` 区域就可以添加文件附件了。

**Comment by No-ideaaa** [comment]
![Screenshot_2019-05-15-12-35-35-920_com tianma tweaks miui](https://user-images.githubusercontent.com/48215946/57750075-4bb8d880-7713-11e9-8376-31d7a6ef3539.png)
一开始是可以用的，后来失效了

**Comment by tianma8023** [comment]
@xiaomengxinyo 
你的时间格式是 `E HH:mm      LOVE YOU EVERYDAY` 吗？ 这个似乎是不可以的，你试试看别的格式。再就是，你升级一下模块版本试试看，已经更新 `1.0.5` 了。
![Screenshot_2019-05-15-13-23-57-595_com tianma twe](https://user-images.githubusercontent.com/7833704/57750440-e36af680-7714-11e9-92b2-2272ec4440bf.png)

**Comment by No-ideaaa** [comment]
@tianma8023 谢谢！确实是我格式不对，我换了别的格式就好了

**Comment by No-ideaaa** [comment]
@tianma8023，那个，大佬问一下，你用的是什么字体😂

**Comment by No-ideaaa** [comment]
@tianma8023，那个，大佬问一下，你用的是什么字体😂

**Comment by tianma8023** [comment]
@xiaomengxinyo 筑紫A丸，可以名为 宁静之雨 的微信公众号里面去找。有对应的magisk模块的。

**Comment by No-ideaaa** [comment]
@tianma8023 好的，谢谢啦！❤️
