### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Justdigit** [tianma8023/XMiuiClock#4]
Since 9.5.9 (MI9) the mod to place the clock on the right side is broken.

The rest like colors etc is still working.

**Comment by tianma8023** [comment]
@justintime1976  Sorry, I forgot to upload the newly mod to Xposed Module Repository. U can download the new version now.

**Comment by Justdigit** [comment]
Ow haha and I didn't look further in Github.

Stupid...

Op 18 mei 2019 13:40:13 schreef Tianma <notifications@github.com>:

**Comment by Justdigit** [comment]
I have installed but still the clock is not moving.?

Op 18 mei 2019 13:40:13 schreef Tianma <notifications@github.com>:

**Comment by tianma8023** [comment]
@justintime1976 try to reboot the system and restart the host apps.

**Comment by Justdigit** [comment]
Yeah I did. But nothing happens.

Op 18 mei 2019 14:15:40 schreef Tianma <notifications@github.com>:

**Comment by Justdigit** [comment]
By the way Gravitybox works.... But Iike to use your app because the clock 
replacement is the only thing i use.

BTW I am on 9.5.16 now.

Op 18 mei 2019 14:15:40 schreef Tianma <notifications@github.com>:

**Comment by Justdigit** [comment]
Reinstalled another 9.5.16 miui Rom. And it's working again.
