### ISSUE TITLE
可以更新到9.8.xx吗，谢谢大佬

### ISSUE THREAD

**Issue by 838514984** [tianma8023/XMiuiClock#6]

**Comment by tianma8023** [comment]
@838514984 这个具体我不清楚，因为我还没升到最新的，貌似他们升上去的人说这个模块可以继续使用。你可以试试看。

**Comment by 838514984** [comment]
@tianma8023 谢谢，因为我是这个版本，用不了才来提的

**Comment by tianma8023** [comment]
@838514984 你可以加一下qq群，反馈问题，模块里面有入口。
