### ISSUE TITLE
Statusbar Clock day

### ISSUE THREAD

**Issue by sakarya1980** [tianma8023/XMiuiClock#7]
Please add day in upper and lowerformat on the clock. Works good on miui 11

**Comment by tianma8023** [comment]
@sakarya1980 you mean the clock time format like "13:05:23" ?

**Comment by sakarya1980** [comment]
Like Thu 07:07

Tianma <notifications@github.com> schrieb am Do., 9. Jan. 2020, 07:05:

**Comment by sakarya1980** [comment]
I add EEE to custom clock, now works :)
![Screenshot_2020-01-09-07-08-56-485_ch deletescape lawnchair ci](https://user-images.githubusercontent.com/32611264/72042602-4c5c3b80-32af-11ea-8d43-f1ee72d6f040.jpg)

**Comment by tianma8023** [comment]
@sakarya1980 you can refer this thread [Java SimpleDateFormat](http://tutorials.jenkov.com/java-internationalization/simpledateformat.html) if you want to know more about the pattern syntax and examples.
